# Generated by Django 5.2.9 on 2026-04-11 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('website', models.CharField(max_length=255)),
                ('admin_url', models.CharField(blank=True, max_length=255)),
                ('owner', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('renewal_date', models.DateField()),
                ('subscription', models.CharField(choices=[('3M', '3M'), ('6M', '6M'), ('9M', '9M'), ('12M', '12M')], max_length=10)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Suspended', 'Suspended'), ('Expired', 'Expired'), ('Deleted', 'Deleted')], max_length=15)),
                ('created', models.DateField(auto_now_add=True)),
                ('expires', models.DateField()),
                ('is_running', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='salons.salon')),
            ],
        ),
    ]
